version: '3'

services:

 planner:
    build:
      context: ./planner
      dockerfile: DockerFile
    ports:
      - "3000:3000"

    networks:
      - planner-worker
      

 worker:
    container_name: worker1
    build:
      context: ./worker
      dockerfile: Dockerfile
    ports:
      - "8080:8080"
    networks:
      - planner-worker

 worker1:
    container_name: worker2
    build:
      context: ./worker
      dockerfile: Dockerfile
    ports:
      - "8070:8080"
    networks:
      - planner-worker

networks:
  planner-worker:
    external: true

#docker network create planner-worker
#docker network ls